spring.application.name=gateway
server.port=8090

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.httpserver.wiretap=true
spring.cloud.gateway.httpclient.wiretap=true

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty.http.client=DEBUG
logging.level.reactor.netty.http.server=DEBUG

spring.cloud.gateway.routes[0].id=User-Service-Swagger
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE-SWAGGER
spring.cloud.gateway.routes[0].predicates[0]=Path=/service1/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=notification-service
spring.cloud.gateway.routes[1].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/notification/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

management.endpoints.web.exposure.include=gateway,health,info
management.endpoint.gateway.enabled=true



